[package]
name = "agent"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.2", features = ["full"] }
anyhow = "1.0.98"
common = { path = "../common" }
# serde = { version = "1.0", features = ["derive"] }
bincode = "2.0.1"

[features]
default = ["tcp"]
tcp = []
