[package]
name = "operator"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.2", features = ["full"] }
anyhow = "1.0.98"
bincode = "2.0.1"
common = { path = "../common" }
shell-words = "1.1.0"
